<template>
  <main class="ancf-detail" :style="cssVars">
    <header class="topbar">
      <button class="icon-btn" type="button" aria-label="Back" @click="$emit('back')">&lt;</button>
      <p>{{ shopLabel }}</p>
      <span class="status"><i></i>{{ manifestStatus }}</span>
    </header>

    <section class="hero">
      <div class="media-shell">
        <img v-if="heroImage" :src="heroImage" :alt="product.title" loading="eager" />
        <span v-else>{{ product.title.slice(0, 2).toUpperCase() }}</span>
      </div>
      <div class="gallery" v-if="gallery.length > 1">
        <button
          v-for="(image, index) in gallery"
          :key="image"
          type="button"
          :class="{ active: activeImage === index }"
          @click="activeImage = index"
        >
          <img :src="image" :alt="`${product.title} ${index + 1}`" loading="lazy" />
        </button>
      </div>
    </section>

    <section class="summary">
      <div class="sku-row">
        <code>{{ product.sku_id }}</code>
        <span>{{ stockText }}</span>
      </div>
      <h1>{{ product.title }}</h1>
      <div class="price-row">
        <strong>{{ formattedPrice }}</strong>
        <span>backend quote required</span>
      </div>
      <p class="description">
        {{ product.description || 'Agent-rendered product detail. Display data is not authoritative for checkout.' }}
      </p>
    </section>

    <section class="spec-grid" aria-label="Specifications">
      <article v-for="(value, key) in product.specs" :key="key">
        <span>{{ key }}</span>
        <strong>{{ value }}</strong>
      </article>
    </section>

    <section class="protocol">
      <div>
        <p>Protocol</p>
        <strong>{{ protocolVersion }}</strong>
      </div>
      <div>
        <p>Bridge Command</p>
        <code>ancf:quote</code>
      </div>
      <div>
        <p>Trust Boundary</p>
        <strong>Backend Authoritative</strong>
      </div>
    </section>

    <section class="safety">
      <strong>Security notice</strong>
      <p>
        This local view is generated by an Agent. Price, stock, payment status, and service activation
        must be confirmed by backend quote and checkout APIs.
      </p>
    </section>

    <footer class="action-bar">
      <div>
        <span>Total preview</span>
        <strong>{{ formattedPrice }}</strong>
      </div>
      <button type="button" class="secondary" @click="emitSelect">Select</button>
      <button type="button" class="primary" @click="emitQuote">Request Quote</button>
    </footer>
  </main>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';

type Price = {
  currency: string;
  amount_minor: string;
  scale: number;
};

export type AncfProductDetail = {
  sku_id: string;
  title: string;
  description?: string;
  price: Price;
  stock_hint?: number;
  specs?: Record<string, string>;
  media?: { thumbnail?: string; gallery?: string[] };
};

const props = withDefaults(defineProps<{
  product: AncfProductDetail;
  shopLabel?: string;
  manifestStatus?: string;
  protocolVersion?: string;
  theme?: Record<string, string>;
}>(), {
  shopLabel: 'ANCF Shop',
  manifestStatus: 'manifest active',
  protocolVersion: 'ANCF-1.0',
  theme: () => ({}),
});

const emit = defineEmits<{
  select: [item: AncfProductDetail];
  quote: [item: AncfProductDetail];
  back: [];
}>();

const activeImage = ref(0);

const cssVars = computed(() => ({
  '--ancf-primary': props.theme.primary || '#00FFA3',
  '--ancf-background': props.theme.background || '#F8FAFC',
  '--ancf-text': props.theme.text || '#111827',
  '--ancf-surface': props.theme.surface || '#FFFFFF',
  '--ancf-border': props.theme.border || '#E5E7EB',
  '--ancf-muted': props.theme.muted || '#6B7280',
  '--ancf-warning': props.theme.warning || '#FFAA00',
}));

const gallery = computed(() => {
  const images = props.product.media?.gallery?.length
    ? props.product.media.gallery
    : props.product.media?.thumbnail
      ? [props.product.media.thumbnail]
      : [];
  return images.filter(Boolean);
});

const heroImage = computed(() => gallery.value[activeImage.value] || props.product.media?.thumbnail || '');

const formattedPrice = computed(() => {
  const price = props.product.price;
  const value = Number(BigInt(price.amount_minor)) / 10 ** price.scale;
  return `${value.toFixed(Math.min(price.scale, 6))} ${price.currency}`;
});

const stockText = computed(() => {
  const stock = props.product.stock_hint;
  if (stock === undefined) return 'stock hidden';
  if (stock === 0) return 'out of stock';
  if (stock < 10) return `${stock} left`;
  return `${stock} available`;
});

function emitSelect(): void {
  emit('select', props.product);
}

function emitQuote(): void {
  emit('quote', props.product);
}
</script>

<style scoped>
.ancf-detail {
  min-height: 100vh;
  background: var(--ancf-background);
  color: var(--ancf-text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  padding: 12px 12px 88px;
}

.topbar,
.summary,
.spec-grid article,
.protocol,
.safety,
.action-bar {
  background: var(--ancf-surface);
  border: 1px solid var(--ancf-border);
  border-radius: 8px;
}

.topbar {
  display: flex;
  align-items: center;
  gap: 12px;
  min-height: 52px;
  padding: 8px 10px;
}

.icon-btn,
.primary,
.secondary,
.gallery button {
  border: 1px solid var(--ancf-border);
  border-radius: 8px;
  background: transparent;
  color: inherit;
  cursor: pointer;
}

.icon-btn {
  width: 36px;
  height: 36px;
}

.topbar p {
  margin: 0;
  font-weight: 700;
}

.status {
  margin-left: auto;
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: var(--ancf-muted);
  font-size: 11px;
}

.status i {
  width: 6px;
  height: 6px;
  border-radius: 999px;
  background: var(--ancf-primary);
}

.hero {
  margin-top: 12px;
}

.media-shell {
  display: grid;
  place-items: center;
  aspect-ratio: 1 / 0.82;
  border: 1px solid var(--ancf-border);
  border-radius: 8px;
  background: #111827;
  color: var(--ancf-primary);
  overflow: hidden;
}

.media-shell img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.gallery {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
  margin-top: 8px;
}

.gallery button {
  aspect-ratio: 1;
  padding: 0;
  overflow: hidden;
}

.gallery button.active {
  border-color: var(--ancf-primary);
}

.gallery img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.summary {
  margin-top: 12px;
  padding: 16px;
}

.sku-row,
.price-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.sku-row code,
.price-row span,
.protocol p,
.safety p,
.action-bar span {
  color: var(--ancf-muted);
  font-size: 12px;
}

.sku-row code {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

h1 {
  margin: 12px 0 0;
  font-size: clamp(28px, 9vw, 52px);
  line-height: 0.96;
  letter-spacing: 0;
}

.price-row {
  margin-top: 16px;
}

.price-row strong {
  color: #003920;
  background: var(--ancf-primary);
  border-radius: 999px;
  padding: 6px 10px;
  font-size: 17px;
}

.description {
  margin: 14px 0 0;
  color: var(--ancf-muted);
  line-height: 1.55;
}

.spec-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
  margin-top: 12px;
}

.spec-grid article {
  padding: 12px;
}

.spec-grid span,
.protocol p,
.safety strong {
  display: block;
  color: var(--ancf-muted);
  font-size: 11px;
  text-transform: uppercase;
}

.spec-grid strong,
.protocol strong,
.protocol code {
  display: block;
  margin-top: 4px;
  font-size: 13px;
}

.protocol {
  margin-top: 12px;
  display: grid;
  gap: 1px;
  overflow: hidden;
}

.protocol > div {
  padding: 12px;
}

.safety {
  margin-top: 12px;
  padding: 12px;
  border-color: var(--ancf-warning);
}

.safety strong {
  color: #A16207;
}

.safety p {
  margin: 6px 0 0;
}

.action-bar {
  position: fixed;
  left: 12px;
  right: 12px;
  bottom: 12px;
  display: grid;
  grid-template-columns: 1fr auto auto;
  align-items: center;
  gap: 8px;
  padding: 8px;
}

.action-bar strong {
  display: block;
  font-size: 13px;
}

.primary,
.secondary {
  min-height: 38px;
  padding: 0 12px;
}

.primary {
  border-color: var(--ancf-primary);
  background: var(--ancf-primary);
  color: #003920;
  font-weight: 700;
}

@media (min-width: 900px) {
  .ancf-detail {
    max-width: 1180px;
    margin: 0 auto;
    display: grid;
    grid-template-columns: minmax(0, 1.1fr) minmax(360px, 0.9fr);
    gap: 12px;
  }

  .topbar,
  .action-bar {
    grid-column: 1 / -1;
  }

  .hero,
  .summary {
    margin-top: 0;
  }

  .spec-grid,
  .protocol,
  .safety {
    grid-column: 2;
  }

  .protocol {
    grid-template-columns: 1fr;
  }
}
</style>
